services:
  vue-app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "5173:5173"
    environment:
      UID: ${UID}
      GID: ${GID}
      NODE_ENV: ${NODE_ENV}
    user: "${UID}:${GID}"  
